# Generated by Django 2.1.3 on 2018-11-26 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='age')),
                ('sex', models.IntegerField(choices=[(1, 'male'), (2, 'female')], default=1, verbose_name='sex')),
                ('memo', models.TextField(blank=True, max_length=300, null=True, verbose_name='remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registration date')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
    ]
