# Generated by Django 2.1.3 on 2023-04-12 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='roll_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Roll No'),
        ),
        migrations.AddField(
            model_name='item',
            name='section',
            field=models.CharField(blank=True, max_length=2, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='memo',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='student Remarks'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female')], default=1, verbose_name='gender'),
        ),
    ]
